# Generated by Django 4.2.28 on 2026-02-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fefu_lab', '0002_instructor_student_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='Пароль'),
        ),
    ]
