# Generated by Django 4.2.28 on 2026-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fefu_lab', '0005_instructor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'Отлично'), ('B', 'Хорошо'), ('C', 'Удовлетворительно'), ('D', 'Неудовлетворительно')], max_length=1, null=True, verbose_name='Оценка'),
        ),
    ]
